version: "3"
services:
  feesh-api:
    image: docker.io/1f47e/feesh-api:latest
      #restart: on-failure:3
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      RPC_USER: 'rpcuser'
      RPC_PASS: 'rpcpass'
      RPC_HOST: 'http://localhost:8334'
      RPC_LIMIT: '420'
      API_HOST: 'localhost:8080'
      BLOCKS_PARSING_DEPTH: 0